### PR TITLE
feature: add option to limit number of parallel tasks.

### PR DESCRIPTION
**Pull request by cgc**

### CODE REVIEW

**Comment by cgc** [comment]
ping @iammerrick

**Comment by iammerrick** [comment]
Can you bump the version number to 0.5 and then I'll merge and publish.

**Comment by cgc** [comment]
@iammerrick rebased, added a test, bumped the version. appreciate you looking at this change, it's been a key part of "fast deployment with 100% uptime" on my projects!

**Comment by cgc** [comment]
@iammerrick let me know if you'd like other changes added!

**Comment by hhaidar** [comment]
+1

**Comment by cgc** [comment]
@iammerrick let me know if there's anything I can do to help get this merged!

**Comment by stephen** [comment]
+1

**Comment by oliversong** [comment]
+1

**Comment by sebadom** [comment]
i guess this was dropped out? @cgc this would be nice

**Comment by cgc** [comment]
@sebadom this wasn't merged in two years, so I'm just going to close the request. Feel free to take these commits and open a new PR!

**Pull request closed without merging**
